ITEM.name = "Aluminum Ore"
ITEM.model = "models/props_mining/rock2_1.mdl"
ITEM.description = "Aluminum ore used for crafting."
ITEM.category = "Crafting Material"
ITEM.width = 1
ITEM.height = 1
ITEM.color = Color(132,135,137)
ITEM.isOre = true
ITEM.ore_chance = 4