ITEM.name = "Copper Ore"
ITEM.model = "models/props_mining/rock2_1.mdl"
ITEM.description = "Copper ore used for crafting."
ITEM.category = "Crafting Material"
ITEM.width = 1
ITEM.height = 1
ITEM.color = Color(139, 69, 19)
ITEM.isOre = true
ITEM.ore_chance = 5