ITEM.name = "Coal"
ITEM.model = "models/props_mining/rock2_1.mdl"
ITEM.description = "Coal used for crafting."
ITEM.category = "Crafting Material"
ITEM.width = 1
ITEM.height = 1
ITEM.color = Color(30, 30, 30)
ITEM.isOre = true
ITEM.ore_chance = 7