ITEM.name = "Gold Ore"
ITEM.model = "models/props_mining/rock2_1.mdl"
ITEM.description = "Gold ore used for crafting."
ITEM.category = "Crafting Material"
ITEM.width = 1
ITEM.height = 1
ITEM.color = Color(255, 215, 0)
ITEM.isOre = true
ITEM.ore_chance = 0.6