ITEM.name = "Silver Ore"
ITEM.model = "models/props_mining/rock2_1.mdl"
ITEM.description = "Silver ore used for crafting."
ITEM.category = "Crafting Material"
ITEM.width = 1
ITEM.height = 1
ITEM.color = Color(192, 192, 192)
ITEM.isOre = true
ITEM.ore_chance = 3