ITEM.name = "Steel Ore"
ITEM.model = "models/props_mining/rock2_1.mdl"
ITEM.description = "Steel ore used for crafting."
ITEM.category = "Crafting Material"
ITEM.width = 1
ITEM.height = 1
ITEM.color = Color(141, 146, 150)
ITEM.isOre = true
ITEM.ore_chance = 2